language: node_js
node_js:
- "node"
script:
  - npm run lint
  - npm run build
  - cp ./src/next.config.js ./dist/next.config.js
  - npm run --prefix dist export
  - cp ./now.json ./dist/out/now.json
before_deploy:
  - npm install now --no-save
deploy:
- provider: script
  script: now ./dist/out --token $NOW_TOKEN
  skip_cleanup: true
  on:
    all_branches: true
    production: false
- provider: script
  script: now ./dist/out --token $NOW_TOKEN && now alias --token $NOW_TOKEN
  skip_cleanup: true
  on:
    branch: production
